// <auto-generated />
using System;
using CalorieCore.Data.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieCore.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405112827_AddMacroGoals")]
    partial class AddMacroGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieCore.DataModels.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("CalorieCore.DataModels.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 350,
                            Description = "Fresh mixed greens topped with grilled chicken breast and light vinaigrette.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chicken breast, Mixed greens, Cherry tomatoes, Cucumber, Olive oil, Lemon juice",
                            Instructions = "1. Grill chicken and slice. 2. Chop vegetables. 3. Toss with olive oil and lemon dressing.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-carb, Light",
                            Title = "Grilled Chicken Salad",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 280,
                            Description = "Classic oatmeal topped with fresh berries and honey.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Oats, Milk, Blueberries, Strawberries, Honey",
                            Instructions = "1. Cook oats with milk. 2. Top with berries. 3. Drizzle honey.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-fiber, Quick, Healthy",
                            Title = "Oatmeal with Berries",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 400,
                            Description = "Nutritious quinoa bowl with roasted vegetables.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Quinoa, Zucchini, Bell peppers, Carrots, Olive oil",
                            Instructions = "1. Cook quinoa. 2. Roast vegetables. 3. Combine and drizzle olive oil.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Balanced",
                            Title = "Quinoa Vegetable Bowl",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 300,
                            Description = "Layered Greek yogurt with granola and fresh fruit.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Greek yogurt, Granola, Mixed berries, Honey",
                            Instructions = "1. Layer yogurt and granola. 2. Add berries. 3. Drizzle honey.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Quick, Healthy",
                            Title = "Greek Yogurt Parfait",
                            Type = "Snack"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 450,
                            Description = "Oven-baked salmon served with roasted asparagus.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Salmon fillet, Asparagus, Olive oil, Lemon, Garlic",
                            Instructions = "1. Season salmon. 2. Bake at 200°C for 15 minutes. 3. Roast asparagus alongside.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Omega-3, Low-carb",
                            Title = "Baked Salmon with Asparagus",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 420,
                            Description = "Quick stir fry with chicken and colorful vegetables.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Chicken breast, Broccoli, Carrots, Bell peppers, Soy sauce",
                            Instructions = "1. Cook chicken strips. 2. Add vegetables. 3. Stir in soy sauce and cook until tender.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Quick, Balanced",
                            Title = "Chicken Stir Fry",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 380,
                            Description = "Whole grain sandwich with turkey and fresh avocado.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Whole grain bread, Turkey slices, Avocado, Lettuce, Tomato",
                            Instructions = "1. Toast bread. 2. Add turkey and sliced avocado. 3. Top with lettuce and tomato.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Quick, Balanced",
                            Title = "Turkey Avocado Sandwich",
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 290,
                            Description = "Egg omelette filled with fresh vegetables.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Eggs, Spinach, Mushrooms, Bell peppers, Olive oil",
                            Instructions = "1. Whisk eggs. 2. Sauté vegetables. 3. Pour eggs over vegetables and cook until set.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Low-carb, High-protein, Quick",
                            Title = "Veggie Omelette",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 330,
                            Description = "Hearty lentil soup packed with fiber and nutrients.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Red lentils, Onion, Carrots, Garlic, Vegetable broth",
                            Instructions = "1. Sauté onion and garlic. 2. Add lentils and broth. 3. Simmer 25 minutes.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Meal prep",
                            Title = "Lentil Soup",
                            Type = "Soup"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 320,
                            Description = "Simple Italian salad with mozzarella and tomatoes.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Mozzarella, Tomatoes, Fresh basil, Olive oil, Balsamic glaze",
                            Instructions = "1. Slice mozzarella and tomatoes. 2. Layer with basil. 3. Drizzle olive oil and balsamic.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Fresh, Light",
                            Title = "Caprese Salad",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 11,
                            Calories = 350,
                            Description = "Creamy smoothie with banana and peanut butter.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Banana, Peanut butter, Milk, Ice",
                            Instructions = "1. Add all ingredients to blender. 2. Blend until smooth.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Energy boost, Quick, Protein",
                            Title = "Peanut Butter Banana Smoothie",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 12,
                            Calories = 430,
                            Description = "Grilled chicken served with brown rice and fresh Mediterranean vegetables.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chicken breast, Brown rice, Cucumber, Cherry tomatoes, Feta cheese, Olive oil, Lemon juice, Oregano",
                            Instructions = "1. Grill seasoned chicken breast and slice. 2. Cook brown rice. 3. Chop vegetables. 4. Assemble bowl and drizzle with olive oil and lemon.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Balanced, Meal prep",
                            Title = "Mediterranean Chicken Bowl",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 13,
                            Calories = 360,
                            Description = "A vegetarian wrap packed with fiber-rich chickpeas and fresh vegetables.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Whole wheat tortilla, Chickpeas, Paprika, Cumin, Lettuce, Tomato, Greek yogurt",
                            Instructions = "1. Sauté chickpeas with paprika and cumin. 2. Warm tortilla. 3. Add vegetables and yogurt. 4. Wrap tightly and serve.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Quick, High-fiber",
                            Title = "Spicy Chickpea Wrap",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 14,
                            Calories = 340,
                            Description = "High-protein oatmeal topped with berries and almond butter.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Oats, Milk, Protein powder, Blueberries, Almond butter",
                            Instructions = "1. Cook oats with milk. 2. Stir in protein powder. 3. Top with blueberries and almond butter.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Energy boost, Healthy",
                            Title = "Protein Oat Breakfast Bowl",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 15,
                            Calories = 390,
                            Description = "Lean turkey patties grilled and seasoned with herbs.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Lean ground turkey, Garlic, Onion, Parsley, Salt, Pepper",
                            Instructions = "1. Mix turkey with seasonings. 2. Form patties. 3. Grill 5-6 minutes per side until fully cooked.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-fat, Dinner",
                            Title = "Grilled Turkey Patties",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 16,
                            Calories = 310,
                            Description = "Low-carb zucchini noodles tossed in fresh basil pesto.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Zucchini, Basil pesto, Cherry tomatoes, Parmesan",
                            Instructions = "1. Spiralize zucchini. 2. Lightly sauté for 2-3 minutes. 3. Stir in pesto and top with tomatoes and parmesan.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Low-carb, Vegetarian, Light",
                            Title = "Zucchini Noodles with Pesto",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 17,
                            Calories = 350,
                            Description = "Oven-baked cod fillet flavored with lemon zest and fresh herbs.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Cod fillet, Olive oil, Lemon zest, Garlic, Parsley, Salt, Pepper",
                            Instructions = "1. Preheat oven to 200°C. 2. Season cod with herbs and lemon. 3. Bake 12-15 minutes until flaky.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-fat, Omega-3",
                            Title = "Baked Cod with Lemon Herbs",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 18,
                            Calories = 290,
                            Description = "Whole grain toast topped with mashed avocado and a perfectly cooked egg.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Whole grain bread, Avocado, Egg, Chili flakes, Salt",
                            Instructions = "1. Toast bread. 2. Mash avocado on top. 3. Add fried or poached egg. 4. Sprinkle chili flakes.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Quick, Balanced, Healthy fats",
                            Title = "Avocado Egg Toast",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 19,
                            Calories = 280,
                            Description = "Light homemade soup with lean chicken and fresh vegetables.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Chicken breast, Carrots, Celery, Onion, Garlic, Chicken broth",
                            Instructions = "1. Sauté vegetables. 2. Add diced chicken and broth. 3. Simmer 20 minutes until chicken is cooked.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Light, High-protein, Meal prep",
                            Title = "Chicken and Vegetable Soup",
                            Type = "Soup"
                        },
                        new
                        {
                            Id = 20,
                            Calories = 260,
                            Description = "Protein-rich cottage cheese topped with fresh fruit.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Cottage cheese, Pineapple, Strawberries, Chia seeds",
                            Instructions = "1. Add cottage cheese to bowl. 2. Top with fruit and chia seeds.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Quick, Healthy",
                            Title = "Cottage Cheese Fruit Bowl",
                            Type = "Snack"
                        },
                        new
                        {
                            Id = 21,
                            Calories = 440,
                            Description = "Lean beef stir fried with colorful vegetables.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Lean beef strips, Bell peppers, Broccoli, Soy sauce, Garlic, Olive oil",
                            Instructions = "1. Cook beef strips in olive oil. 2. Add vegetables and stir fry 5 minutes. 3. Add soy sauce and cook 2 more minutes.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Dinner, Balanced",
                            Title = "Healthy Beef Stir Fry",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 22,
                            Calories = 310,
                            Description = "Fluffy omelette filled with spinach and feta cheese.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Eggs, Fresh spinach, Feta cheese, Olive oil, Salt, Pepper",
                            Instructions = "1. Whisk eggs. 2. Sauté spinach. 3. Add eggs and feta. 4. Cook until set.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-carb, Quick",
                            Title = "Spinach and Feta Omelette",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 23,
                            Calories = 420,
                            Description = "Grilled shrimp served over quinoa with avocado and tomatoes.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Shrimp, Quinoa, Avocado, Cherry tomatoes, Lime juice, Olive oil",
                            Instructions = "1. Grill shrimp. 2. Cook quinoa. 3. Assemble bowl and drizzle lime juice.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Omega-3, Balanced",
                            Title = "Grilled Shrimp Quinoa Bowl",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 24,
                            Calories = 400,
                            Description = "Bell peppers stuffed with lean turkey and brown rice.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Bell peppers, Lean ground turkey, Spinach, Brown rice, Garlic, Tomato sauce",
                            Instructions = "1. Cook turkey with spinach. 2. Mix with rice. 3. Stuff peppers and bake 25 minutes.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Meal prep, Healthy",
                            Title = "Turkey and Spinach Stuffed Peppers",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 25,
                            Calories = 330,
                            Description = "Fresh salad combining chickpeas and creamy avocado.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chickpeas, Avocado, Red onion, Lemon juice, Olive oil, Parsley",
                            Instructions = "1. Combine ingredients. 2. Toss with lemon and olive oil.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Light",
                            Title = "Avocado Chickpea Salad",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 26,
                            Calories = 360,
                            Description = "Roasted sweet potato topped with garlic yogurt sauce.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Sweet potato, Greek yogurt, Garlic, Paprika, Olive oil",
                            Instructions = "1. Bake sweet potato. 2. Prepare yogurt sauce. 3. Top and serve.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Comfort food",
                            Title = "Baked Sweet Potato with Yogurt Sauce",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 27,
                            Calories = 390,
                            Description = "Light whole wheat wrap filled with grilled chicken and Caesar-style salad.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Grilled chicken, Whole wheat tortilla, Romaine lettuce, Light Caesar dressing, Parmesan",
                            Instructions = "1. Slice grilled chicken. 2. Add to tortilla with lettuce and dressing. 3. Sprinkle parmesan and wrap tightly.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Quick, Lunch",
                            Title = "Chicken Caesar Wrap Light",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 28,
                            Calories = 410,
                            Description = "Fresh Greek salad topped with seasoned grilled chicken breast.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chicken breast, Cucumber, Tomato, Olives, Feta, Olive oil, Oregano",
                            Instructions = "1. Grill chicken and slice. 2. Chop vegetables. 3. Toss with olive oil and oregano. 4. Top with feta.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Mediterranean, Balanced",
                            Title = "Greek Salad with Grilled Chicken",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 29,
                            Calories = 300,
                            Description = "Thick smoothie bowl blended with berries and protein powder.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Banana, Frozen berries, Protein powder, Almond milk, Chia seeds",
                            Instructions = "1. Blend banana, berries, protein powder and milk. 2. Pour into bowl. 3. Top with chia seeds.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Energy boost, Healthy",
                            Title = "Protein Smoothie Bowl",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 30,
                            Calories = 340,
                            Description = "Oven-baked tilapia infused with lemon and garlic flavors.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Tilapia fillet, Lemon juice, Garlic, Olive oil, Parsley, Salt",
                            Instructions = "1. Season tilapia with garlic and lemon. 2. Bake 12-15 minutes at 200°C. 3. Garnish with parsley.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Low-fat, High-protein, Dinner",
                            Title = "Lemon Garlic Tilapia",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 31,
                            Calories = 370,
                            Description = "Plant-based stir fry with tofu and colorful vegetables.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Firm tofu, Broccoli, Carrots, Bell peppers, Soy sauce, Sesame oil",
                            Instructions = "1. Cook tofu cubes until golden. 2. Add vegetables and stir fry 5 minutes. 3. Add soy sauce and sesame oil.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-protein, Balanced",
                            Title = "Vegetable Stir Fry with Tofu",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 32,
                            Calories = 390,
                            Description = "Healthy brown rice fried with eggs and vegetables.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Brown rice, Eggs, Green peas, Carrots, Soy sauce, Green onion",
                            Instructions = "1. Scramble eggs in pan. 2. Add cooked rice and vegetables. 3. Stir in soy sauce and green onions.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Balanced, Quick, Comfort food",
                            Title = "Egg Fried Brown Rice",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 33,
                            Calories = 420,
                            Description = "Low-carb salad with grilled chicken and creamy avocado.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chicken breast, Avocado, Mixed greens, Cherry tomatoes, Olive oil, Lemon",
                            Instructions = "1. Grill chicken and slice. 2. Combine with greens and vegetables. 3. Drizzle olive oil and lemon.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-carb, Healthy fats",
                            Title = "Grilled Chicken Avocado Salad",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 34,
                            Calories = 430,
                            Description = "Whole wheat pasta mixed with tuna and sautéed spinach.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Whole wheat pasta, Canned tuna, Spinach, Olive oil, Garlic",
                            Instructions = "1. Cook pasta. 2. Sauté garlic and spinach. 3. Mix with tuna and pasta.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Balanced, Quick",
                            Title = "Healthy Tuna Pasta",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 35,
                            Calories = 310,
                            Description = "Protein-rich pancakes made with cottage cheese and oats.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Cottage cheese, Eggs, Oats, Baking powder",
                            Instructions = "1. Blend all ingredients. 2. Cook small pancakes on medium heat 2-3 minutes per side.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Healthy, Quick",
                            Title = "Cottage Cheese Pancakes",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 36,
                            Calories = 380,
                            Description = "Roasted seasonal vegetables served over quinoa.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Zucchini, Eggplant, Bell peppers, Olive oil, Quinoa",
                            Instructions = "1. Roast chopped vegetables 25 minutes at 200°C. 2. Serve over cooked quinoa.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Balanced",
                            Title = "Roasted Vegetable Bowl",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 37,
                            Calories = 450,
                            Description = "Crispy whole wheat quesadilla filled with chicken and avocado.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Whole wheat tortilla, Grilled chicken, Avocado, Light cheese",
                            Instructions = "1. Fill tortilla with chicken, avocado and cheese. 2. Cook in pan until crispy on both sides.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = false,
                            Tags = "High-protein, Quick, Comfort food",
                            Title = "Chicken and Avocado Quesadilla",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 38,
                            Calories = 290,
                            Description = "Healthy baked oatmeal cut into portable squares.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Oats, Milk, Eggs, Honey, Blueberries",
                            Instructions = "1. Mix ingredients. 2. Pour into baking dish. 3. Bake 25 minutes at 180°C and slice.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-fiber, Meal prep, Breakfast",
                            Title = "Baked Oatmeal Squares",
                            Type = "Snack"
                        },
                        new
                        {
                            Id = 39,
                            Calories = 410,
                            Description = "Soft tacos filled with grilled chicken and fresh vegetables.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chicken breast, Corn tortillas, Lettuce, Tomato, Greek yogurt",
                            Instructions = "1. Grill chicken and slice. 2. Fill tortillas with chicken and vegetables. 3. Top with yogurt.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Quick, Dinner",
                            Title = "Grilled Chicken Tacos",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 40,
                            Calories = 420,
                            Description = "Hearty vegetarian curry with red lentils and spinach.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Red lentils, Spinach, Onion, Garlic, Coconut milk, Curry powder",
                            Instructions = "1. Cook onion and garlic. 2. Add lentils, coconut milk and curry powder. 3. Simmer 20 minutes. 4. Stir in spinach.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Meal prep",
                            Title = "Lentil and Spinach Curry",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 41,
                            Calories = 270,
                            Description = "Greek yogurt bowl with apple slices, cinnamon and honey.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Greek yogurt, Apple, Cinnamon, Honey, Walnuts",
                            Instructions = "1. Add yogurt to bowl. 2. Top with apple and walnuts. 3. Sprinkle cinnamon and drizzle honey.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Quick, Healthy, Light",
                            Title = "Apple Cinnamon Yogurt Bowl",
                            Type = "Snack"
                        },
                        new
                        {
                            Id = 42,
                            Calories = 460,
                            Description = "Sweet and savory glazed salmon served with steamed broccoli.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Salmon fillet, Honey, Soy sauce, Garlic, Broccoli, Lemon",
                            Instructions = "1. Mix honey, soy sauce, and garlic. 2. Brush over salmon. 3. Bake at 200°C for 12-15 minutes. 4. Steam broccoli as a side.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Omega-3, Dinner",
                            Title = "Honey Garlic Glazed Salmon",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 43,
                            Calories = 210,
                            Description = "A lean, high-protein breakfast with fluffy egg whites and sautéed peppers.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Egg whites, Bell peppers, Spinach, Onion, Salt, Pepper",
                            Instructions = "1. Sauté peppers and onions. 2. Pour in egg whites. 3. Scramble until firm. 4. Stir in fresh spinach at the end.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Low-fat, High-protein, Quick",
                            Title = "Egg White Veggie Scramble",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 44,
                            Calories = 480,
                            Description = "Whole wheat pasta tossed with grilled chicken and a light basil pesto.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Whole wheat pasta, Chicken breast, Basil pesto, Cherry tomatoes, Pine nuts",
                            Instructions = "1. Cook pasta. 2. Grill and slice chicken. 3. Toss pasta with pesto, tomatoes, and chicken. 4. Garnish with pine nuts.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Balanced, Mediterranean",
                            Title = "Pesto Chicken Pasta",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 45,
                            Calories = 280,
                            Description = "Refreshing spinach salad with strawberries, blueberries, and walnuts.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Baby spinach, Strawberries, Blueberries, Walnuts, Balsamic vinaigrette",
                            Instructions = "1. Toss spinach with fresh berries. 2. Add walnuts for crunch. 3. Drizzle with balsamic vinaigrette.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Antioxidants, Light",
                            Title = "Berry Spinach Salad",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 46,
                            Calories = 370,
                            Description = "Hearty and warming chili made with lean ground turkey and beans.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Ground turkey, Kidney beans, Diced tomatoes, Chili powder, Onion, Bell pepper",
                            Instructions = "1. Brown the turkey with onions and peppers. 2. Add tomatoes, beans, and spices. 3. Simmer for 30 minutes on low heat.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-fiber, Meal prep, High-protein",
                            Title = "Turkey Chili",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 47,
                            Calories = 330,
                            Description = "Elevated breakfast toast with creamy avocado and smoked salmon.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Whole grain bread, Avocado, Smoked salmon, Red onion, Capers",
                            Instructions = "1. Toast the bread. 2. Mash avocado and spread evenly. 3. Top with salmon, onion slices, and capers.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Healthy fats, Omega-3, Quick",
                            Title = "Avocado Toast with Smoked Salmon",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 48,
                            Calories = 410,
                            Description = "Lean beef strips and broccoli florets in a ginger-garlic sauce.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Beef sirloin, Broccoli, Soy sauce, Ginger, Garlic, Sesame oil",
                            Instructions = "1. Stir fry beef until browned. 2. Add broccoli and a splash of water to steam. 3. Stir in sauce and cook until thick.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-carb, Quick",
                            Title = "Beef and Broccoli",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 49,
                            Calories = 240,
                            Description = "Overnight chia pudding made with almond milk and vanilla.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Chia seeds, Almond milk, Vanilla extract, Stevia, Raspberries",
                            Instructions = "1. Mix chia seeds, milk, and vanilla. 2. Refrigerate overnight. 3. Top with raspberries before serving.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-fiber, Plant-based, Snack",
                            Title = "Chia Seed Pudding",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 50,
                            Calories = 350,
                            Description = "Crunchy roasted chickpeas over a bed of kale and tahini dressing.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Chickpeas, Kale, Tahini, Lemon, Garlic, Olive oil",
                            Instructions = "1. Roast chickpeas until crispy. 2. Massage kale with olive oil. 3. Top kale with chickpeas and tahini dressing.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, High-fiber, Gluten-free",
                            Title = "Roasted Chickpea Salad",
                            Type = "Salad"
                        },
                        new
                        {
                            Id = 51,
                            Calories = 440,
                            Description = "Classic roasted chicken thighs with rosemary and lemon.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Chicken thighs, Rosemary, Lemon, Garlic, Butter, Salt",
                            Instructions = "1. Rub chicken with garlic and herbs. 2. Place lemon slices on top. 3. Roast at 190°C for 35-40 minutes.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Comfort food, Dinner",
                            Title = "Lemon Herb Roasted Chicken",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 52,
                            Calories = 290,
                            Description = "Clear vegetable soup with small pasta and Italian herbs.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Carrots, Celery, Zucchini, Tomato paste, Vegetable broth, Small pasta",
                            Instructions = "1. Sauté veggies. 2. Add broth and tomato paste. 3. Add pasta and simmer until tender.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Low-calorie, Healthy",
                            Title = "Vegetable Minestrone Soup",
                            Type = "Soup"
                        },
                        new
                        {
                            Id = 53,
                            Calories = 320,
                            Description = "Baked eggplant layers with marinara and low-fat mozzarella.",
                            Difficulty = "Medium",
                            Img = "",
                            Ingredients = "Eggplant, Marinara sauce, Low-fat mozzarella, Parmesan, Basil",
                            Instructions = "1. Slice and bake eggplant. 2. Layer with sauce and cheese. 3. Bake until bubbly and golden.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Balanced, Dinner",
                            Title = "Eggplant Parmigiana Light",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 54,
                            Calories = 310,
                            Description = "Quick lunch featuring tuna salad served inside avocado halves.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Canned tuna, Avocado, Greek yogurt, Celery, Lime juice",
                            Instructions = "1. Mix tuna with yogurt and celery. 2. Scoop out a bit of avocado. 3. Fill with tuna mixture.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Low-carb, High-protein, No-cook",
                            Title = "Tuna Stuffed Avocado",
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 55,
                            Calories = 340,
                            Description = "Oatmeal that tastes like freshly baked banana bread.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Oats, Ripe banana, Walnuts, Cinnamon, Milk",
                            Instructions = "1. Cook oats with milk. 2. Stir in mashed banana and cinnamon. 3. Top with crushed walnuts.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-fiber, Vegetarian, Quick",
                            Title = "Banana Bread Oats",
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 56,
                            Calories = 280,
                            Description = "Succulent shrimp sautéed in a light garlic butter sauce.",
                            Difficulty = "Easy",
                            Img = "",
                            Ingredients = "Shrimp, Garlic, Butter, Parsley, Lemon, Red pepper flakes",
                            Instructions = "1. Sauté garlic in butter. 2. Add shrimp and cook 2 minutes per side. 3. Finish with lemon and parsley.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Low-carb, Quick",
                            Title = "Garlic Butter Shrimp",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 57,
                            Calories = 520,
                            Description = "A sophisticated dish featuring lean beef tenderloin wrapped in mushroom duxelles and light pastry.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Beef tenderloin, Mushrooms, Shallots, Thyme, Dijon mustard, Prosciutto (lean), Phyllo pastry, Egg wash",
                            Instructions = "1. Sear beef tenderloin on all sides and chill. 2. Finely chop mushrooms and sauté with shallots and thyme until all moisture evaporates (Duxelles). 3. Spread mustard on beef. 4. Layer prosciutto, then duxelles, then beef on plastic wrap and roll tightly into a log; chill for 1 hour. 5. Wrap the log in phyllo pastry, brush with egg wash, and bake at 200°C until the pastry is golden and internal temp is 52°C.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Gourmet, High-protein, High-effort",
                            Title = "Beef Wellington Bites (Lean Edition)",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 58,
                            Calories = 480,
                            Description = "Fresh pasta made from scratch, filled with a delicate spinach and ricotta mixture in a light sage butter.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Type 00 flour, Eggs, Fresh spinach, Ricotta cheese, Nutmeg, Parmesan, Fresh sage, Butter, Garlic",
                            Instructions = "1. Create a flour mound, add eggs in the center, and knead for 10 minutes until smooth; rest for 30 minutes. 2. Blanch spinach, squeeze out ALL moisture, and mix with ricotta, nutmeg, and parmesan. 3. Roll pasta dough into thin sheets using a machine. 4. Place dollops of filling, fold over, seal without air bubbles, and cut into squares. 5. Boil for 3 minutes and toss in a pan with browned butter and crispy sage leaves.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Italian, Handmade",
                            Title = "Handmade Spinach & Ricotta Ravioli",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 59,
                            Calories = 550,
                            Description = "Authentic Spanish saffron rice cooked slowly with an array of fresh seafood and aromatics.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Bomba rice, Saffron threads, Shrimp, Mussels, Squid, Chicken thighs, Bell peppers, Tomatoes, Smoked paprika, Seafood stock",
                            Instructions = "1. Sauté chicken and squid in a wide paella pan; remove. 2. Create a 'sofrito' by slowly cooking onions, peppers, and grated tomatoes until dark and jammy. 3. Add rice and toast slightly, then add saffron-infused stock. 4. Simmer WITHOUT STIRRING to develop the 'socarrat' (crispy bottom). 5. Arrange shrimp and mussels on top for the last 8 minutes, allowing them to steam as the liquid disappears.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Seafood, Spanish, One-pan",
                            Title = "Traditional Seafood Paella",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 60,
                            Calories = 410,
                            Description = "A deep, rich soup requiring hours of onion caramelization for a complex, sweet-savory flavor profile.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Yellow onions (2kg), Beef bone broth, Dry white wine, Cognac, Flour, Thyme, Bay leaf, Baguette slices, Gruyère cheese",
                            Instructions = "1. Slice onions thinly and cook in a heavy pot on low heat for 60-90 minutes, stirring occasionally until deep mahogany brown. 2. Deglaze with cognac and white wine, scraping the bottom. 3. Stir in flour, then slowly add beef broth and herbs. 4. Simmer for 45 minutes to develop depth. 5. Ladle into oven-safe bowls, top with toasted baguette and a thick layer of Gruyère, and broil until bubbly and charred.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = false,
                            Tags = "French, Comfort food, High-effort",
                            Title = "French Onion Soup (Authentic)",
                            Type = "Soup"
                        },
                        new
                        {
                            Id = 61,
                            Calories = 620,
                            Description = "Slow-cooked lamb shanks that fall off the bone, served in a reduced wine and root vegetable jus.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Lamb shanks, Red wine (Cabernet), Carrots, Celery, Leeks, Garlic, Rosemary, Tomato paste, Lamb stock",
                            Instructions = "1. Season and brown lamb shanks deeply in a Dutch oven; remove. 2. Sauté mirepoix (carrots, celery, leeks) until soft. 3. Add tomato paste and cook until it darkens. 4. Return lamb to the pot, cover halfway with wine and stock. 5. Braise at 150°C for 3.5 hours. 6. Strain the liquid into a saucepan and reduce by half until it coats a spoon; pour over the lamb to serve.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "High-protein, Slow-cook, Gourmet",
                            Title = "Braised Lamb Shanks in Red Wine",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 62,
                            Calories = 580,
                            Description = "A labor-intensive Greek classic with spiced meat sauce, fried eggplant, and thick béchamel topping.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Eggplants, Potatoes, Ground lamb, Cinnamon, Allspice, Onions, Red wine, Milk, Flour, Butter, Egg yolks, Kefalotyri cheese",
                            Instructions = "1. Slice and salt eggplants to remove bitterness; rinse and bake until soft. 2. Fry potato slices for the base layer. 3. Cook lamb with onions, wine, and warm spices (cinnamon/allspice) until thick. 4. Make a roux with butter and flour, whisk in milk until thick, then temper with egg yolks and cheese for the béchamel. 5. Layer potatoes, meat, eggplant, then béchamel; bake at 180°C for 50 minutes until golden brown.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = false,
                            Tags = "Greek, Traditional, Layered",
                            Title = "Eggplant Moussaka (Layered)",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 63,
                            Calories = 320,
                            Description = "Restaurant-quality cold appetizer requiring precision knife work and fresh, high-grade ingredients.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Sashimi-grade Ahi Tuna, Shallots, Chives, Ginger, Soy sauce, Sesame oil, Lime, Ripe avocado, Wasabi, Microgreens",
                            Instructions = "1. Chill all equipment. 2. Use a razor-sharp knife to dice tuna into perfect 5mm cubes. 3. Mix tuna with finely minced shallots, chives, ginger, and dressing. 4. Blend avocado with lime and wasabi until completely smooth; pass through a fine sieve. 5. Use a ring mold to layer the tuna on a plate, top with dots of avocado mousse using a piping bag, and garnish with microgreens.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Seafood, Low-carb, Precision",
                            Title = "Tuna Tartare with Avocado Mousse",
                            Type = "Appetizer"
                        },
                        new
                        {
                            Id = 64,
                            Calories = 450,
                            Description = "A technical Italian dish requiring constant attention to achieve the perfect 'all'onda' consistency.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Arborio rice, Dried porcini, Fresh cremini, Shiitake, Shallots, Dry vermouth, Mushroom stock, Butter, Parmesan, Truffle oil",
                            Instructions = "1. Rehydrate porcini and keep stock simmering nearby. 2. Sauté mushrooms in batches to ensure browning; remove. 3. Toast rice with shallots until edges are translucent. 4. Add vermouth and reduce. 5. Add stock ONE LADLE AT A TIME, stirring constantly to release starch. 6. Once rice is al dente, vigorously beat in cold butter and parmesan (Mantucatura) to create a creamy sauce. 7. Drizzle with truffle oil.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vegetarian, Italian, Technique",
                            Title = "Wild Mushroom Risotto with Truffle Oil",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 65,
                            Calories = 490,
                            Description = "Vietnamese noodle soup featuring a clear, deeply aromatic broth made from charred aromatics and bones.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Beef marrow bones, Star anise, Cinnamon sticks, Cardamom, Charred ginger, Charred onion, Rice noodles, Flank steak, Fish sauce",
                            Instructions = "1. Parboil bones for 10 minutes, then scrub clean to ensure a clear broth. 2. Simmer bones for 12-24 hours, skimming fat constantly. 3. Toast spices and add to broth with charred ginger and onion for the final 4 hours. 4. Strain through a cheesecloth and season with fish sauce. 5. Serve with blanched rice noodles, paper-thin raw steak slices (cooked by the hot broth), and fresh herbs.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Vietnamese, High-effort, Aromatic",
                            Title = "Authentic Pho (24-Hour Broth)",
                            Type = "Soup"
                        },
                        new
                        {
                            Id = 66,
                            Calories = 540,
                            Description = "Technical dish combining modern sous-vide precision with classic French sauce reduction.",
                            Difficulty = "Hard",
                            Img = "",
                            Ingredients = "Duck breast, Fresh cherries, Red wine vinegar, Sugar, Port wine, Star anise, Thyme, Parsnip puree",
                            Instructions = "1. Score duck skin in a diamond pattern without hitting the meat. 2. Vacuum seal with thyme and cook in water bath at 54°C for 2 hours. 3. Create a gastrique by caramelizing sugar, deglazing with vinegar and port, and reducing with cherries until syrupy. 4. Sear duck in a cold pan, rendering out all fat until skin is paper-thin and crispy. 5. Rest meat, slice, and serve over parsnip puree with the reduction.",
                            IsFavorite = false,
                            IsGlobal = true,
                            IsHealthy = true,
                            Tags = "Gourmet, Precision, French",
                            Title = "Sous-Vide Duck Breast with Cherry Gastrique",
                            Type = "Main"
                        });
                });

            modelBuilder.Entity("CalorieCore.DataModels.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ActivityMultiplier")
                        .HasColumnType("float");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyCarbGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyFatGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyProteinGoal")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("CalorieCore.DataModels.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CalorieCore.DataModels.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CalorieCore.DataModels.Meal", b =>
                {
                    b.HasOne("CalorieCore.DataModels.UserAccount", "UserAccount")
                        .WithMany("Meals")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CalorieCore.DataModels.Recipe", b =>
                {
                    b.HasOne("CalorieCore.DataModels.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CalorieCore.DataModels.UserAccount", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("CalorieCore.DataModels.UserActivity", b =>
                {
                    b.HasOne("CalorieCore.DataModels.UserAccount", "UserAccount")
                        .WithMany("Activities")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CalorieCore.DataModels.WeightLog", b =>
                {
                    b.HasOne("CalorieCore.DataModels.UserAccount", "UserAccount")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieCore.DataModels.UserAccount", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Meals");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
