// <auto-generated />
using System;
using CalorieCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieCore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128143633_AddRecipeSeedAndImg")]
    partial class AddRecipeSeedAndImg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieCore.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 350,
                            Description = "A healthy and protein-packed salad with grilled chicken, fresh greens, tomatoes, and a light vinaigrette.",
                            Img = "~/images/grilled-chicken.jpg",
                            IsHealthy = true,
                            Title = "Grilled Chicken Salad"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 250,
                            Description = "Whole-grain toast topped with smashed avocado, cherry tomatoes, and a sprinkle of sesame seeds.",
                            Img = "~/images/avocado-toast.jpg",
                            IsHealthy = true,
                            Title = "Avocado Toast"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 650,
                            Description = "Classic Italian pasta with creamy egg sauce, pancetta, and Parmesan cheese.",
                            Img = "~/images/pasta-carbonara.jpg",
                            IsHealthy = false,
                            Title = "Pasta Carbonara"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 300,
                            Description = "A refreshing smoothie bowl with blended fruits, granola, and fresh berries.",
                            Img = "~/images/smoothie-bowl.jpg",
                            IsHealthy = true,
                            Title = "Smoothie Bowl"
                        });
                });

            modelBuilder.Entity("CalorieCore.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CalorieCore.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CalorieCore.Models.UserActivity", b =>
                {
                    b.HasOne("CalorieCore.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
